//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CeyGlass.Web.SupplierServiceReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="SupplierServiceReference.ISupplierService")]
    public interface ISupplierService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISupplierService/SignIn", ReplyAction="http://tempuri.org/ISupplierService/SignInResponse")]
        CeyGlass.DataTransfer.Responses.SignInResponseDto SignIn(CeyGlass.DataTransfer.Requests.SignInRequestDto request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISupplierService/SignIn", ReplyAction="http://tempuri.org/ISupplierService/SignInResponse")]
        System.Threading.Tasks.Task<CeyGlass.DataTransfer.Responses.SignInResponseDto> SignInAsync(CeyGlass.DataTransfer.Requests.SignInRequestDto request);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ISupplierServiceChannel : CeyGlass.Web.SupplierServiceReference.ISupplierService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SupplierServiceClient : System.ServiceModel.ClientBase<CeyGlass.Web.SupplierServiceReference.ISupplierService>, CeyGlass.Web.SupplierServiceReference.ISupplierService {
        
        public SupplierServiceClient() {
        }
        
        public SupplierServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SupplierServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SupplierServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SupplierServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public CeyGlass.DataTransfer.Responses.SignInResponseDto SignIn(CeyGlass.DataTransfer.Requests.SignInRequestDto request) {
            return base.Channel.SignIn(request);
        }
        
        public System.Threading.Tasks.Task<CeyGlass.DataTransfer.Responses.SignInResponseDto> SignInAsync(CeyGlass.DataTransfer.Requests.SignInRequestDto request) {
            return base.Channel.SignInAsync(request);
        }
    }
}
